import { Lesson } from '../../../types/curriculum';

export const beginnerLesson: Lesson = {
  id: 'p8-beginner',
  title: 'Introduction to DeFi',
  level: 'beginner',
  cards: [
    { id: 'b1', type: 'concept', title: 'What is DeFi?', content: 'DeFi stands for Decentralized Finance. It is an entirely new financial system built on blockchains (mostly Ethereum) that operates without banks, brokers, or central authorities.'
    },
    { id: 'b2', type: 'insight', title: 'The Problem with TradFi', content: 'In Traditional Finance (TradFi), if you want a loan, you must ask a bank for permission. They check your credit score, take days to process paperwork, and take a massive cut of the interest. In DeFi, you interact directly with code.'
    },
    { id: 'b3', type: 'example', title: 'The Permissionless Bank', content: 'In DeFi, if you want a $10,000 loan, you simply deposit $15,000 worth of Bitcoin into a smart contract as collateral, and you instantly receive the loan. No credit check. No human permission. It executes in 10 seconds.'
    },
    { id: 'b4', type: 'exercise', title: 'DeFi vs TradFi', content: 'What is the core difference between Decentralized Finance (DeFi) and Traditional Finance (TradFi)?', options: ['DeFi only uses US Dollars.', 'DeFi removes human middlemen, allowing users to trade, borrow, and lend directly via automated smart contracts.', 'TradFi is faster and cheaper.'], correctAnswer: 'DeFi removes human middlemen, allowing users to trade, borrow, and lend directly via automated smart contracts.'
    },
    { id: 'b5', type: 'concept', title: 'Non-Custodial Wallets', content: 'To use DeFi, you must have a Non-Custodial Wallet (like MetaMask). This means YOU hold the private keys. The wallet connects directly to the dApp website to sign transactions.'
    },
    { id: 'b6', type: 'warning', title: 'The Ultimate Responsibility', content: 'Because there is no bank, there is no password reset button. If you lose your seed phrase, or approve a malicious smart contract, your money is gone instantly.'
    },
    { id: 'b7', type: 'concept', title: 'DEX vs CEX', content: 'A CEX (Centralized Exchange like Coinbase) holds your crypto and matches buyers and sellers using an internal ledger. A DEX (Decentralized Exchange like Uniswap) allows you to trade directly from your wallet using smart contracts.'
    },
    { id: 'b8', type: 'insight', title: 'The AMM Revolution', content: 'A DEX doesn\'t use an "Order Book" of buyers and sellers. It uses an Automated Market Maker (AMM). It is a giant pool of tokens controlled by a mathematical formula (x * y = k).'
    },
    { id: 'b9', type: 'example', title: 'The Liquidity Pool', content: 'Imagine a giant glass bowl filled with exactly 100 Apples and 100 Oranges. If you take an Apple out, the algorithm automatically increases the price of the remaining Apples, and lowers the price of the Oranges.'
    },
    { id: 'b10', type: 'exercise', title: 'Exchange Types', content: 'What technology does a Decentralized Exchange (DEX) like Uniswap use to price assets without an order book?', options: ['An Automated Market Maker (AMM) algorithm.', 'A central banker.', 'A high-frequency trading firm.'], correctAnswer: 'An Automated Market Maker (AMM) algorithm.'
    },
    { id: 'b11', type: 'concept', title: 'Liquidity Providers (LPs)', content: 'Where do the tokens in the DEX pool come from? Regular users! You can deposit your own tokens into the smart contract to provide liquidity for other people to trade against.'
    },
    { id: 'b12', type: 'insight', title: 'Earning Trading Fees', content: 'As a reward for providing liquidity, the smart contract automatically pays you a portion of every trading fee generated by the pool. You become the exchange.'
    },
    { id: 'b13', type: 'concept', title: 'Yield Farming', content: 'Yield Farming is the act of hunting for the highest interest rates across different DeFi protocols. You provide liquidity to a protocol, and they reward you with high yields (often paid in their native token).'
    },
    { id: 'b14', type: 'warning', title: 'The APY Illusion', content: 'If a DeFi protocol offers 1,000% APY, they are just printing their own worthless token out of thin air to pay you. When the token price inevitably crashes to zero, your 1,000% yield is worth nothing.'
    },
    { id: 'b15', type: 'exercise', title: 'Yield Logic', content: 'How do users earn passive income on a Decentralized Exchange (DEX)?', options: ['By watching ads.', 'By depositing their tokens into a Liquidity Pool and earning a share of the trading fees.', 'By hacking the protocol.'], correctAnswer: 'By depositing their tokens into a Liquidity Pool and earning a share of the trading fees.'
    },
    { id: 'b16', type: 'concept', title: 'Over-Collateralized Lending', content: 'Because DeFi protocols don\'t know your credit score, all loans must be Over-Collateralized. To borrow $100, you must deposit $150 worth of assets.'
    },
    { id: 'b17', type: 'insight', title: 'Why borrow if you have the money?', content: 'You believe Ethereum will go up. You don\'t want to sell your ETH to pay rent. So, you deposit your ETH as collateral, borrow USDC (stablecoin) to pay rent, and keep your ETH exposure.'
    },
    { id: 'b18', type: 'warning', title: 'Liquidation', content: 'If the price of your Ethereum collateral drops too low, the smart contract will automatically sell your ETH to repay the loan, plus a massive penalty fee. This is a Liquidation.'
    },
    { id: 'b19', type: 'exercise', title: 'DeFi Lending', content: 'Why do DeFi loans require Over-Collateralization?', options: ['To punish the borrower.', 'Because smart contracts cannot check credit scores or legally collect debts, so the collateral guarantees repayment.', 'To pay the government.'], correctAnswer: 'Because smart contracts cannot check credit scores or legally collect debts, so the collateral guarantees repayment.'
    },
    { id: 'b20', type: 'concept', title: 'Staking', content: 'Staking is locking up your crypto in a protocol to help secure the network (Proof of Stake) or provide liquidity. In return, you earn a steady yield.'
    },
    { id: 'b21', type: 'concept', title: 'Impermanent Loss', content: 'The biggest risk of being a Liquidity Provider. If you provide liquidity for ETH and USDC, and ETH skyrockets in price, the AMM algorithm forces you to sell your winning ETH for losing USDC as the pool rebalances.'
    },
    { id: 'b22', type: 'insight', title: 'The Opportunity Cost', content: 'If a token moons, you would have made more money just holding it in your wallet than putting it in a liquidity pool. The loss is "impermanent" until you withdraw, at which point it becomes a permanent loss of potential profit.'
    },
    { id: 'b23', type: 'exercise', title: 'The LP Risk', content: 'What is Impermanent Loss?', options: ['When you forget your password.', 'The potential loss of profit a Liquidity Provider suffers when the price of one asset changes drastically compared to just holding the assets in a wallet.', 'When a token goes to zero.'], correctAnswer: 'The potential loss of profit a Liquidity Provider suffers when the price of one asset changes drastically compared to just holding the assets in a wallet.'
    },
    { id: 'b24', type: 'concept', title: 'Bridges', content: 'Blockchains are isolated. A Bridge is a protocol that allows you to move your tokens from Ethereum to another chain (like Solana). It works by locking your token on Chain A and minting a copy on Chain B.'
    },
    { id: 'b25', type: 'warning', title: 'Bridge Hacks', content: 'Because bridges hold massive amounts of locked collateral, they are the #1 target for hackers. Over $2 Billion was stolen from bridges in 2022 alone.'
    },
    { id: 'b26', type: 'concept', title: 'The Web3 Ethos', content: 'Web1 was Read (Static websites). Web2 was Read/Write (Social Media, but corporations own your data). Web3 is Read/Write/Own (You own your data and assets cryptographically).'
    },
    { id: 'b27', type: 'insight', title: 'Composability (Money Legos)', content: 'Because DeFi is open-source, developers can stack protocols together like Legos. You can take a loan from Protocol A, deposit it into Protocol B, and use the yield to buy insurance on Protocol C, all in one click.'
    },
    { id: 'b28', type: 'warning', title: 'Systemic Risk', content: 'Because everything is connected (Money Legos), if one foundational protocol gets hacked, the entire house of cards can collapse instantly.'
    },
    { id: 'b29', type: 'concept', title: 'Summary', content: 'DeFi is building a parallel, permissionless financial system. It offers incredible yields and freedom, but the risks (hacks, liquidations, impermanent loss) are entirely on your shoulders.'
    },
    { id: 'b30', type: 'concept', title: 'Live Scenario', content: 'Test your understanding of DeFi Liquidation in a live scenario.', tool: 'dynamic',
      toolProps: {
        scenario: "You deposit $10,000 worth of ETH into a DeFi lending protocol as collateral. You borrow $5,000 in USDC to buy a car. The Liquidation Threshold is 80%. Suddenly, the crypto market crashes and your ETH value drops to $6,000.",
        startingBalance: 10000,
        choices: [
          { text: "Do nothing and hope the market recovers tomorrow.", result: -6000, feedback: "You got Liquidated! Because your borrowed amount ($5,000) exceeded 80% of your collateral's new value ($6,000), the smart contract automatically sold your ETH, took the $5k back, and charged you a massive penalty. You lost your collateral." },
          { text: "Quickly deposit another $4,000 of ETH to increase your collateral ratio.", result: 0, feedback: "Smart move. By depositing more collateral, you lowered your loan-to-value ratio, avoiding the automated liquidation. You live to fight another day." },
          { text: "Call customer support to ask for an extension.", result: -6000, feedback: "There is no customer support in DeFi. Code is law. The smart contract liquidated you instantly while you were searching for a phone number." }
        ]
      }
    }
  ]
};
