import { Lesson } from '../../../types/curriculum';

export const intermediateLesson: Lesson = {
  id: 'p10-intermediate',
  title: 'NFT Valuation & Communities',
  level: 'intermediate',
  cards: [
    { id: 'i1', type: 'concept', title: 'Valuing the Invaluable', content: 'How do you value an NFT? Unlike a stock (which has cash flow) or a token (which has utility), most NFTs are purely subjective art. Their value is derived entirely from community, culture, and scarcity.'
    },
    { id: 'i2', type: 'insight', title: 'The Veblen Good', content: 'In economics, a Veblen Good is a luxury item where demand INCREASES as the price increases, because it acts as a status symbol. An expensive NFT is the ultimate digital Veblen Good.'
    },
    { id: 'i3', type: 'example', title: 'The Rolex Analogy', content: 'A $10 Casio watch tells time better than a $50,000 Rolex. You buy the Rolex to signal wealth to others. You buy a CryptoPunk to signal wealth to the global internet.'
    },
    { id: 'i4', type: 'exercise', title: 'Valuation Psychology', content: 'Why do some pixelated NFTs sell for millions of dollars?', options: ['Because the pixels are made of gold.', 'Because they act as digital Veblen Goods, signaling extreme wealth and status to a global audience.', 'Because they pay dividends.'], correctAnswer: 'Because they act as digital Veblen Goods, signaling extreme wealth and status to a global audience.'
    },
    { id: 'i5', type: 'concept', title: 'Rarity Traits', content: 'Most PFP (Profile Picture) collections have 10,000 items. They are generated by an algorithm that randomly combines traits (hats, eyes, fur color). Some traits are mathematically rarer than others.'
    },
    { id: 'i6', type: 'insight', title: 'The Floor Price', content: 'The "Floor Price" is the absolute cheapest NFT you can buy in a specific collection. If the floor is 10 ETH, you cannot join the community for less than 10 ETH.'
    },
    { id: 'i7', type: 'concept', title: 'Rarity vs Floor', content: 'An NFT with common traits will sell exactly at the Floor Price. An NFT with ultra-rare traits (like a laser-eyes alien) might sell for 100x the Floor Price.'
    },
    { id: 'i8', type: 'warning', title: 'Liquidity at the Top', content: 'A rare NFT might be "worth" 100x the floor, but finding a buyer willing to pay that massive premium is incredibly difficult. The Floor NFTs are always the most liquid.'
    },
    { id: 'i9', type: 'exercise', title: 'Market Mechanics', content: 'What is the "Floor Price" of an NFT collection?', options: ['The price the original artist was paid.', 'The lowest price at which any NFT in the collection is currently listed for sale.', 'The average price of all past sales.'], correctAnswer: 'The lowest price at which any NFT in the collection is currently listed for sale.'
    },
    { id: 'i10', type: 'concept', title: 'The Community Moat', content: 'The only thing stopping someone from launching a clone of a successful NFT project is the Community. A strong, rabid community forms a defensive "moat" around the brand.'
    },
    { id: 'i11', type: 'insight', title: 'Utility vs Culture', content: 'Some projects promise utility (e.g., "Buy this NFT and get a free t-shirt"). This usually fails. The projects that survive are the ones that build culture (e.g., "Buy this NFT and become part of this exclusive tribe").'
    },
    { id: 'i12', type: 'concept', title: 'IP Rights (Intellectual Property)', content: 'When you buy a Bored Ape, Yuga Labs gives you full commercial rights to the artwork. You can put your Ape on a coffee brand and sell it. When you buy a CryptoPunk (originally), Larva Labs kept the rights.'
    },
    { id: 'i13', type: 'example', title: 'The IP Shift', content: 'Giving owners commercial rights decentralizes the brand building. If 10,000 people are legally incentivized to build businesses using their NFT, the overall brand grows exponentially without the founders lifting a finger.'
    },
    { id: 'i14', type: 'exercise', title: 'Brand Growth', content: 'Why do some NFT collections give commercial IP rights to the buyers?', options: ['Because it is legally required.', 'To incentivize 10,000 owners to build products and businesses using the art, decentralizing the growth of the brand.', 'Because they hate their own art.'], correctAnswer: 'To incentivize 10,000 owners to build products and businesses using the art, decentralizing the growth of the brand.'
    },
    { id: 'i15', type: 'concept', title: 'Wash Trading', content: 'A malicious tactic where a person buys their own NFT using a different wallet. They sell it back and forth to themselves at higher and higher prices to trick the market into thinking there is massive demand.'
    },
    { id: 'i16', type: 'warning', title: 'Fake Volume', content: 'A project might show $1 Million in trading volume, but it\'s just the founders wash trading. You buy in, and suddenly realize there are zero real buyers. You are trapped.'
    },
    { id: 'i17', type: 'concept', title: 'Airdrops & Derivative Collections', content: 'To keep the community engaged, successful projects often "airdrop" a free secondary NFT to the holders of the original NFT (e.g., Bored Apes airdropping Mutant Serums).'
    },
    { id: 'i18', type: 'insight', title: 'Value Dilution', content: 'While airdrops feel like free money, they essentially print new supply. If a project launches too many derivative collections, they dilute the exclusivity of the brand and crash the price.'
    },
    { id: 'i19', type: 'exercise', title: 'Market Manipulation', content: 'What is Wash Trading?', options: ['Cleaning physical art.', 'Selling an NFT back and forth between two wallets you own to create fake volume and artificially inflate the price.', 'Paying taxes on a sale.'], correctAnswer: 'Selling an NFT back and forth between two wallets you own to create fake volume and artificially inflate the price.'
    },
    { id: 'i20', type: 'concept', title: 'Fractionalization', content: 'If an NFT is worth $1 Million, 99.9% of people cannot afford it. Fractionalization locks the NFT in a vault and issues 1 Million ERC-20 tokens representing shares of the NFT.'
    },
    { id: 'i21', type: 'insight', title: 'Solving Liquidity', content: 'Fractionalization solves the NFT illiquidity problem. You can now sell $100 worth of a CryptoPunk instantly on Uniswap, instead of waiting months to find a buyer for the whole Punk.'
    },
    { id: 'i22', type: 'warning', title: 'The SEC Risk', content: 'The moment you fractionalize an asset and sell shares with the expectation of profit, you cross the line into traditional finance. The SEC considers fractionalized NFTs to be unregistered securities.'
    },
    { id: 'i23', type: 'exercise', title: 'Fractional Ownership', content: 'What is the primary benefit of Fractionalizing an expensive NFT?', options: ['It makes the image quality better.', 'It creates massive liquidity, allowing anyone to buy and sell micro-shares of the asset instantly.', 'It prevents the SEC from regulating it.'], correctAnswer: 'It creates massive liquidity, allowing anyone to buy and sell micro-shares of the asset instantly.'
    },
    { id: 'i24', type: 'concept', title: 'Soulbound Tokens (SBTs)', content: 'An NFT that CANNOT be sold or transferred. Once it is in your wallet, it is there forever.'
    },
    { id: 'i25', type: 'example', title: 'The Digital Resume', content: 'Harvard could issue your diploma as a Soulbound Token. It proves you graduated, but because it is Soulbound, you cannot sell your Harvard degree to someone else.'
    },
    { id: 'i26', type: 'concept', title: 'NFT Lending', content: 'You can now use high-value NFTs as collateral for a loan. You lock your Ape in a smart contract and borrow 50 ETH. If you don\'t pay it back, the contract gives the Ape to the lender.'
    },
    { id: 'i27', type: 'warning', title: 'Cascading Liquidations', content: 'Because NFT prices are so volatile and illiquid, if the floor price drops slightly, loans get liquidated. The smart contracts automatically dump the NFTs on the market, crashing the floor even harder.'
    },
    { id: 'i28', type: 'insight', title: 'The Attention Economy', content: 'In Web3, attention is the most valuable currency. NFTs are simply tools to capture, monetize, and gate attention. The projects that command the most attention win.'
    },
    { id: 'i29', type: 'concept', title: 'Summary', content: 'Evaluating NFTs requires understanding culture, illiquidity, and community dynamics. It is vastly different from evaluating a cash-flowing business. It is the purest form of speculative psychology.'
    },
    { id: 'i30', type: 'concept', title: 'Live Scenario', content: 'Test your understanding of NFT liquidity and loans in a live scenario.', tool: 'dynamic',
      toolProps: {
        scenario: "You own an NFT with a Floor Price of 10 ETH. You need 5 ETH to pay taxes. You lock your NFT in a lending protocol and borrow 5 ETH. The market crashes and the Floor Price drops to 6 ETH.",
        startingBalance: 10,
        choices: [
          { text: "Do nothing and wait for the floor price to recover.", result: -10, feedback: "You got liquidated! Because your loan (5 ETH) became dangerously close to the collateral value (6 ETH), the protocol automatically sold your NFT at a massive discount to protect the lender. You lost your incredibly rare NFT." },
          { text: "Immediately repay the 5 ETH loan out of pocket to unlock the NFT.", result: 0, feedback: "Smart move. You repaid the loan and saved your collateral from liquidation. The NFT is safely back in your wallet, allowing you to ride out the market crash." },
          { text: "Try to sell the NFT while it's locked in the contract.", result: -5, feedback: "You can't sell an asset that is locked in an escrow contract! While you were trying to figure this out, the floor price dropped to 5 ETH and you were liquidated." }
        ]
      }
    }
  ]
};
